displayName=Am I There Yet?
author=Leonardo
description=Shows the minimum XP needed to appear on the HiScores for each skill
tags=hiscores,xp,goals,skills
version=1.0
plugins=com.minhiscores.MinHiscoresPlugin
build=standard